import React from 'react';
import { motion } from 'framer-motion';
import {
  MessageCircle, HeartPulse, BrainCog,
  Gift, CalendarCheck, Users
} from 'lucide-react';

const useCases = [
  {
    icon: <MessageCircle size={32} />,
    title: 'AI Therapist & Buddy',
    desc: 'Have conversations with a supportive AI trained to guide, listen, and help you feel better any time.'
  },
  {
    icon: <HeartPulse size={32} />,
    title: 'Mood Tracking & Journaling',
    desc: 'Track your mood, thoughts, and behaviors to discover emotional patterns and improve well-being.'
  },
  {
    icon: <BrainCog size={32} />,
    title: 'Mental Health Exercises',
    desc: 'Get tailored breathing, CBT, and mindfulness exercises generated by our smart engine or hardware device.'
  },
  {
    icon: <Gift size={32} />,
    title: 'Rewards System',
    desc: 'Earn rewards for consistency, self-reflection, and growth in your healing journey.'
  },
  {
    icon: <CalendarCheck size={32} />,
    title: 'Doctor Appointments',
    desc: 'Easily consult licensed mental health professionals virtually or find nearby help with just a tap.'
  },
  {
    icon: <Users size={32} />,
    title: 'Connect & Meet',
    desc: 'Meet like-minded people facing similar challenges—talk, share, or meet in certified safe spaces near you.'
  },
];

const flowSteps = [
  {
    title: 'Open a Session',
    desc: 'Start chatting with our AI therapist or initiate a session with a doctor or peer.',
    icon: <MessageCircle size={28} />,
  },
  {
    title: 'Track & Reflect',
    desc: 'Log moods, write journals, and analyze trends using our smart mental health engine.',
    icon: <HeartPulse size={28} />,
  },
  {
    title: 'Use Exercises & Tools',
    desc: 'Get recommended activities from AI or use our hardware tools for calming exercises.',
    icon: <BrainCog size={28} />,
  },
  {
    title: 'Book or Meet Someone',
    desc: 'Schedule a virtual doctor appointment or connect with a verified peer at a nearby safe café.',
    icon: <Users size={28} />,
  },
];

function HowItWorks() {
  return (
    <section
      id="how-it-works"
      className="bg-white py-20 px-6 md:px-20 text-gray-800"
    >
      <motion.div 
        initial={{ opacity: 0, y: 30 }} 
        whileInView={{ opacity: 1, y: 0 }} 
        viewport={{ once: true }} 
        transition={{ duration: 0.6 }}
        className="text-center mb-16"
      >
        <h2 className="text-4xl font-bold mb-4">Your Healing Journey</h2>
        <p className="text-gray-600 text-lg max-w-xl mx-auto">
          Discover how Mind Mates empowers you emotionally, socially, and mentally with 360° care.
        </p>
      </motion.div>

      <motion.div
        initial={{ opacity: 0, y: 30 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.6 }}
        className="text-center mb-10"
      >
        <h3 className="text-3xl font-semibold mb-2">What You Can Do with Mind Mates</h3>
      </motion.div>

      <div className="grid gap-10 md:grid-cols-2 lg:grid-cols-3 mb-20">
        {useCases.map((useCase, i) => (
          <motion.div
            key={useCase.title}
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: i * 0.2 }}
            className="bg-[#f7f4fe] p-8 rounded-2xl shadow-md text-center hover:shadow-xl transition"
          >
            <div className="text-[#8f71ff] mb-6 mx-auto w-16 h-16 flex items-center justify-center bg-[#ebe4ff] rounded-full">
              {useCase.icon}
            </div>
            <h3 className="text-xl font-semibold mb-2">{useCase.title}</h3>
            <p className="text-gray-600 text-sm">{useCase.desc}</p>
          </motion.div>
        ))}
      </div>

      <motion.div
        initial={{ opacity: 0, y: 30 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true }}
        transition={{ duration: 0.7 }}
        className="text-center"
      >
        <h3 className="text-3xl font-semibold mb-14">Step-by-Step Support Flow</h3>
        <div className="relative flex flex-col items-center mx-auto max-w-2xl">
          {flowSteps.map((step, i) => (
            <motion.div
              key={step.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: i * 0.2 }}
              className="relative flex items-start mb-16"
            >
              {i !== flowSteps.length - 1 && (
                <div className="absolute left-8 top-16 h-full w-1 bg-[#8f71ff]"></div>
              )}
              <div className="w-16 h-16 flex-shrink-0 rounded-full bg-[#ebe4ff] text-[#8f71ff] flex items-center justify-center z-10 text-2xl">
                {step.icon}
              </div>
              <div className="ml-8 text-left max-w-md">
                <h4 className="text-xl font-semibold mb-2">{`${i + 1}. ${step.title}`}</h4>
                <p className="text-gray-600 text-base">{step.desc}</p>
              </div>
            </motion.div>
          ))}
        </div>
      </motion.div>
    </section>
  );
}

export default HowItWorks;
